# .github/workflows/api-prod-cd.yml
name: Deploy API to PROD

on:
  push:
    branches:
      - main
    paths:
      - 'src/backend/TFST.API/**'
      - 'src/backend/TFST.Modules.**/**'
      - 'src/backend/TFST.SharedKernel.**/**'
      - 'src/TFST.sln'
      - '.github/workflows/api-dev-cd.yml'
      - '.github/workflows/deploy-api.yml'

  workflow_dispatch:

permissions:
  id-token: write
  contents: read
    
jobs:
  deploy_api:
    uses: ./.github/workflows/deploy-backend-project.yml
    with:
      environment: prod
      branch: main
      project_path: src/backend/TFST.API/TFST.API.csproj
      app_service_name: tfst-api-prod
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_PUBLISH_PROFILE: ${{ secrets.AZURE_PUBLISH_PROFILE_API }}
