# .github/workflows/api-dev-cd.yml
name: Deploy API to DEV

on:
  push:
    branches:
      - dev
    paths:
      - 'src/backend/TFST.API/**'
      - 'src/backend/TFST.Modules.**/**'
      - 'src/backend/TFST.SharedKernel.**/**'
      - '.github/workflows/api-dev-cd.yml'
      - '.github/workflows/deploy-api.yml'
  workflow_dispatch:

jobs:
  deploy_api:
    uses: ./.github/workflows/deploy-api.yml
    with:
      environment: dev
      branch: dev
      working_directory: src/api
      solution_name: TheFullStackTeam.Backend.sln
      app_service_name: tfst-api-dev
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
