# .github/workflows/auth-dev-cd.yml
name: Deploy API Container to DEV

on:
  push:
    branches:
      - dev
    paths:
      - 'src/backend/TFST.API/**'
      - 'src/backend/TFST.Modules.**/**'
      - 'src/backend/TFST.SharedKernel.**/**'
      - 'src/TFST.sln'
      - '.github/workflows/api-dev-cd.yml'
      - '.github/workflows/deploy-api.yml'

  workflow_dispatch:

jobs:
  deploy_API:
    uses: ./.github/workflows/deploy-container-project.yml
    with:
      environment: dev
      dockerfile_path: src/backend/TFST.API/Dockerfile
      context: ./src
      image_name: tfst/API
      app_service_name: tfst-api-dev
      acr_login_server: tfstregistry.azurecr.io
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
