# .github/workflows/auth-dev-cd.yml
name: Deploy Auth Server to DEV

on:
  push:
    branches:
      - dev
    paths:
      - 'src/backend/TFST.AuthServer/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy_auth:
    uses: ./.github/workflows/deploy-backend-project.yml
    with:
      environment: dev
      branch: dev
      project_path: src/backend/TFST.AuthServer/TFST.AuthServer.csproj
      app_service_name: tfst-auth-dev
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_PUBLISH_PROFILE: ${{ secrets.AZURE_PUBLISH_PROFILE_AUTH }}
