# .github/workflows/deploy-backend-project.yml
name: Deploy Backend Project

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: "The deployment environment (e.g., dev, prod)"
      branch:
        required: true
        type: string
        description: "The branch being deployed"
      project_path:
        required: true
        type: string
        description: "The relative path to the project to publish (e.g., src/backend/TFST.API/TFST.API.csproj)"
      app_service_name:
        required: true
        type: string
        description: "The Azure App Service name for deployment"
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_PUBLISH_PROFILE:
        required: false

jobs:
  deploy_project:
    name: Deploy Project to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Debug Inputs
        run: |
          echo "Environment: ${{ inputs.environment }}"
          echo "Branch: ${{ inputs.branch }}"
          echo "Project Path: ${{ inputs.project_path }}"
          echo "App Service Name: ${{ inputs.app_service_name }}"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure using OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Publish .NET Project
        run: |
          dotnet publish ${{ inputs.project_path }} \
            --configuration Release \
            --output ${{ github.workspace }}/publish

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ inputs.app_service_name }}
          package: ${{ github.workspace }}/publish
