# .github/workflows/webapp-prod-deploy.yml
name: Deploy Angular WebApp to PROD

on:
  push:
    branches:
      - main
    paths:
      - src/clients/tfst-app/**

  workflow_dispatch:

jobs:
  deploy_tfst_app_prod:
    uses: ./.github/workflows/deploy-angular.yml
    with:
      environment: prod
      working_directory: src/clients/tfst-app/TFST-Front
      app_service_name: tfst-app-prod
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
