# .github/workflows/validate-infra.yml
name: Validate Infrastructure

on:
  workflow_call:
    inputs:      
      environment:
        required: true
        type: string
        description: "The deployment environment (e.g., dev, prod)"
      working_directory:
        required: true
        type: string
        description: "The working directory for the environment (e.g., infrastructure/envs/dev)"
      terraform_modules_directory:
        required: true
        type: string
        description: "The directory for Terraform modules (e.g., infrastructure/modules)"    
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      SQL_ADMIN_PASSWORD:
        required: true
      SQL_ADMIN_USERNAME:
        required: true

jobs:
  validate_infra:
    name: Validate Infrastructure  to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4
          
      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Install Terraform and Terragrunt
      - name: Install Terraform and Terragrunt
        run: |
          sudo apt-get update && sudo apt-get install -y unzip
          curl -fsSL https://releases.hashicorp.com/terraform/1.9.8/terraform_1.9.8_linux_amd64.zip -o terraform.zip
          unzip -o terraform.zip -d /usr/local/bin/
          curl -fsSL https://github.com/gruntwork-io/terragrunt/releases/download/v0.69.0/terragrunt_linux_amd64 -o /usr/local/bin/terragrunt
          chmod +x /usr/local/bin/terragrunt

      # Validate Terraform syntax
      - name: Validate Terraform Syntax
        run: terraform fmt -recursive -check ${{ inputs.terraform_modules_directory }}

      # Validate Terragrunt syntax
      - name: Validate Terragrunt Syntax
        run: |
          cd ${{ inputs.working_directory }}
          terragrunt hclfmt --terragrunt-check

      # Validate Infrastructure Code
      - name: Validate Infrastructure Code
        run: |
          cd ${{ inputs.working_directory }}
          terragrunt run-all validate
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          SQL_ADMIN_PASSWORD: ${{ secrets.SQL_ADMIN_PASSWORD }}
          SQL_ADMIN_USERNAME: ${{ secrets.SQL_ADMIN_USERNAME }}
